package com.testora.core.events;

/** Lifecycle events published on the {@link EventBus}. */
public enum EventType {
    TEST_STARTED, SETUP_STARTED, ACTION_STARTED, WAIT_STARTED, WAIT_COMPLETED,
    ACTION_COMPLETED, ACTION_FAILED, RETRY_STARTED, RECOVERY_STARTED, RECOVERY_COMPLETED,
    AI_ANALYSIS_STARTED, AI_ANALYSIS_COMPLETED, EVIDENCE_CAPTURED,
    TEST_FAILED, TEST_PASSED, CLEANUP_STARTED, TEST_COMPLETED
}
